### ISSUE TITLE
Fix: Alex always sweating

### ISSUE THREAD

**Issue by EnriqueL8** [a-roberts/dragonball#7]
Bring a spare T-shirt?

**Comment by a-roberts** [comment]
We can only land this after gathering the picture for https://github.com/a-roberts/dragonball/issues/5.

**Comment by EnriqueL8** [comment]
I agree

**Comment by gdams** [comment]
play topless?

**Comment by EnriqueL8** [comment]
Too shiny... 🔷

**Comment by al-k21** [comment]
I can bring  a towel and @EnriqueL8 can stay next to me and wipe me if I get sweaty.

**Comment by EnriqueL8** [comment]
I think your Team Angry teammate @a-roberts is more suited for the job

**Comment by a-roberts** [comment]
I think this discussion has gone way off track and so I'm closing it. This repository needs to be in a fine working condition for when we announce it to the world on Reddit and it becomes a massive hit.
